ALTER TABLE PATIENT
 DROP PRIMARY KEY CASCADE;

DROP TABLE PATIENT CASCADE CONSTRAINTS;

CREATE TABLE PATIENT
(
  PATIENT_ID       VARCHAR2(30 BYTE),
  PATIENT_FNAME    VARCHAR2(30 BYTE),
  PATIENT_LNAME    VARCHAR2(30 BYTE),
  PATIENT_PHONE    VARCHAR2(30 BYTE),
  PATIENT_ID_NO    VARCHAR2(30 BYTE),
  PATIENT_ADDRESS  VARCHAR2(30 BYTE),
  PATIENT_DOB      VARCHAR2(30 BYTE),
  CREATE_DT        DATE                         DEFAULT SYSDATE
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PATIENT_PK ON PATIENT
(PATIENT_ID)
LOGGING
TABLESPACE NSNDAT01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PATIENT ADD (
  CONSTRAINT PATIENT_PK
 PRIMARY KEY
 (PATIENT_ID)
    USING INDEX 
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
