ALTER TABLE TRIAGE
 DROP PRIMARY KEY CASCADE;

DROP TABLE TRIAGE CASCADE CONSTRAINTS;

CREATE TABLE TRIAGE
(
  TRIAGE_ID            VARCHAR2(30 BYTE),
  PATIENT_ID           VARCHAR2(30 BYTE),
  TRIAGE_DT_TIME       DATE                     DEFAULT SYSDATE,
  WEIGHT               VARCHAR2(10 BYTE),
  TEMPERATURE          VARCHAR2(10 BYTE),
  FEVER                VARCHAR2(2 BYTE),
  TIREDNESS            VARCHAR2(2 BYTE),
  LOSS_OF_TASTE        VARCHAR2(2 BYTE),
  LOSS_OF_SMELL        VARCHAR2(2 BYTE),
  SORE_THROAT          VARCHAR2(2 BYTE),
  HEADACHE             VARCHAR2(2 BYTE),
  CHEST_PAIN           VARCHAR2(2 BYTE),
  DIFFICULT_BREATHING  VARCHAR2(2 BYTE),
  BREATH_SHORTNESS     VARCHAR2(2 BYTE),
  CREATE_DT            DATE                     DEFAULT SYSDATE
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TRIAGE_PK ON TRIAGE
(TRIAGE_ID)
LOGGING
TABLESPACE NSNDAT01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TRIAGE ADD (
  CONSTRAINT TRIAGE_PK
 PRIMARY KEY
 (TRIAGE_ID)
    USING INDEX 
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE TRIAGE ADD (
  CONSTRAINT PATIENT_ID_FK 
 FOREIGN KEY (PATIENT_ID) 
 REFERENCES PATIENT (PATIENT_ID));
